name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run tests
        run: fastlane test

  deploy:
    name: Deploy to Firebase
    runs-on: macos-latest
    env:
      CI: true 
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Firebase plugin
        run: fastlane add_plugin firebase_app_distribution

      - name: Build & Upload to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: fastlane beta
